#!/bin/bash

# Check if the script is running in Docker
if [ -f "/.dockerenv" ]; then
    # Add or update entries in /etc/hosts
    echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

    echo "Hosts configuration completed."
else
    echo "This script is intended to run in Docker. Exiting."
    exit 1
fi

